name: 'Temporary deploy fix'

on:
  push:
    branches:
      - release-fix

permissions:
  id-token: write # Required for OIDC - see https://docs.npmjs.com/trusted-publishers
  contents: read

jobs:
  version_check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version_changed.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth: 2 is necessary to allow checking the previous commit
          fetch-depth: 2
      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.3.3
      - name: Store package.json
        run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - name: Current version
        run: echo '${{ fromJson(env.PACKAGE_JSON).version }}'
      - name: Version changed
        id: version_changed
        run: echo "version=${{ fromJson(env.PACKAGE_JSON).version }}" >> $GITHUB_OUTPUT
  start_publish:
    needs: [version_check]
    # Only run this job if the version has changed
    if: ${{needs.version_check.outputs.version}}
    uses: nordcraftengine/nordcraft/.github/workflows/deploy_to_npm.yml@release-fix
    with:
      version: ${{needs.version_check.outputs.version}}
    secrets: inherit
